[package]
name = "ykls"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.28.1"
reqwest = { version = "0.12.7", features = ["json"]}
tokio = { version = "1.40.0", features = ["full"]}
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.121"
